apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: python:3.12
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: python-configmap
        - secretRef:
            name: python-secrets
        command: ["python"]
        args: ["-m", "http.server", "8000"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
